import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {parsePostcaptureReference,isPostcaptureReference,verifyPostcaptureCorrectionSource,verifyPostcaptureArchive} from './verify-postcapture-correction-source.mjs';
const read=name=>readFileSync(new URL(`../../contracts/${name}`,import.meta.url));
const requestBytes=read('financial_source_postcapture_request_v1.json'),request=JSON.parse(requestBytes),referenceBytes=read('financial_source_postcapture_reference_v1.json'),contract=JSON.parse(referenceBytes);
const sha=value=>createHash('sha256').update(value).digest('hex');
const blob=value=>createHash('sha1').update(Buffer.concat([Buffer.from(`blob ${value.length}\0`),value])).digest('hex');
const canonical=value=>Array.isArray(value)?`[${value.map(canonical).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${canonical(value[k])}`).join(',')}}`:JSON.stringify(value);
const step=(name,number,conclusion='success',start='2026-10-06T16:00:05Z',end='2026-10-06T16:02:59Z')=>({name,number,conclusion,status:'completed',started_at:start,completed_at:end});
function fixture(){
 const dir=mkdtempSync(join(tmpdir(),'postcapture-reader-small-')),path=join(dir,'companion.zip'),bytes=Buffer.from('synthetic bytes; offline verifier is a direct unit-test dependency');writeFileSync(path,bytes);
 const reference={schema_version:contract.schema_version,repository:contract.repository,workflow:contract.validator_workflow,head_sha:'a'.repeat(40),run_id:12345,run_attempt:1,job_id:23456,artifact_id:34567,artifact_name:`${contract.artifact_prefix}-${'a'.repeat(40)}-1`,artifact_sha256:sha(bytes),receipt_sha256:'0'.repeat(64)};
 const treeSha='b'.repeat(40),gatePath='.github/financial-source-postcapture/request.json';
 const code=Object.fromEntries(contract.required_code_paths.filter(path=>path!==gatePath).map(path=>[path,{sha256:'c'.repeat(64),git_blob_sha:'d'.repeat(40),bytes:1}]));code[gatePath]={sha256:sha(requestBytes),git_blob_sha:blob(requestBytes),bytes:requestBytes.length};
 const entry={reference,tree_sha:treeSha,source:request.source,request:{path:gatePath,raw_sha256:sha(requestBytes),canonical_sha256:sha(canonical(request)),git_blob_sha:blob(requestBytes)},code_manifest:code,controller_contracts:{reference_sha256:sha(referenceBytes),request_sha256:sha(requestBytes),receipt_schema_sha256:sha(read('financial_source_postcapture_receipt_v1.schema.json'))},artifact_layout:{companion_prefix:'synthetic/',files:{},directories:[]},captured_inventory_sha256:request.captured_inventory.sha256,fresh_receipt_inventory_sha256:request.refresh.new_receipt_inventory_sha256};
 const repo={id:1203919607,full_name:contract.repository};
 function attempt(ref,validator){
  const run={id:ref.run_id,run_attempt:ref.run_attempt,head_sha:ref.head_sha,path:ref.workflow,head_branch:validator?contract.validator_branch:'improve/mandatory-financial-source-recovery',event:'push',status:'completed',conclusion:validator?'success':'failure',repository:repo,head_repository:repo,run_started_at:validator?'2026-10-06T16:00:00Z':'2026-10-06T14:24:45Z',head_commit:{tree_id:validator?treeSha:request.producer_tree_sha}};
  const job={id:validator?ref.job_id:request.producer_job_id,run_id:ref.run_id,run_attempt:ref.run_attempt,head_sha:ref.head_sha,name:validator?contract.validator_job:contract.source_job,status:'completed',conclusion:run.conclusion,started_at:validator?'2026-10-06T16:00:01Z':'2026-10-06T14:24:48Z',completed_at:validator?'2026-10-06T16:04:00Z':'2026-10-06T14:40:09Z',steps:validator?['Test exact-source retrieval guards','Test offline companion validation guards','Retrieve only the exact retained source and original job log','Validate captured evidence with acquisition denied','Retain independent validation evidence'].map((name,i)=>step(name,i+1)):[step(request.failure_boundary.failed_step_name,10,'failure','2026-10-06T14:25:55Z','2026-10-06T14:39:56Z')]};
  const artifact={id:ref.artifact_id,name:ref.artifact_name,expired:false,digest:`sha256:${ref.artifact_sha256}`,size_in_bytes:validator?bytes.length:request.artifact_size_bytes,created_at:validator?'2026-10-06T16:03:00Z':'2026-10-06T14:40:06Z',expires_at:'2099-01-01T00:00:00Z',workflow_run:{id:ref.run_id,head_sha:ref.head_sha,head_branch:run.head_branch,repository_id:1203919607,head_repository_id:1203919607}};
  return {run,jobs:[job],artifacts:[artifact]};
 }
 const producer=attempt(request.source,false),certifier=attempt(reference,true);
 const commit={sha:reference.head_sha,tree:{sha:treeSha},parents:[{sha:request.validator.first_parent_sha}]},tree={sha:treeSha,truncated:false,tree:Object.entries(code).map(([path,info])=>({path,type:'blob',mode:'100644',sha:info.git_blob_sha}))};
 const snapshot={run:{...structuredClone(certifier.run),status:'in_progress',conclusion:null},job:{...structuredClone(certifier.jobs[0]),status:'in_progress',conclusion:null},commit,tree};
 const receipt={source:request.source,evaluated_at:'2026-10-06T16:01:30Z',validation:{code_sha:reference.head_sha,tree_sha:treeSha,request_sha256:entry.request.raw_sha256,validator_api_snapshot:{run_id:reference.run_id,run_attempt:1,job_id:reference.job_id,status:'in_progress',authentication:'provided_api_snapshot_requires_independent_authentication',successful_run_attested:false}},producer_execution:{failed_step_number:10,original_final_guard_result:'failed',original_outcomes_retained:true,producer_batch_exit_code:0,producer_cycle_exit_code:0,producer_job_conclusion:'failure',producer_job_id:request.producer_job_id,producer_run_conclusion:'failure'},authority:structuredClone(request.authority)};
 reference.receipt_sha256=sha(canonical(receipt));
 const output={receipt,source_api_evidence:structuredClone(producer),validator_api_snapshot:snapshot};
 const api=endpoint=>{for(const data of [producer,certifier]){const base=`repos/${contract.repository}/actions/runs/${data.run.id}`;if(endpoint===`${base}/attempts/${data.run.run_attempt}`)return structuredClone(data.run);if(endpoint===`${base}/attempts/${data.run.run_attempt}/jobs?per_page=100`)return {total_count:data.jobs.length,jobs:structuredClone(data.jobs)};if(endpoint===`${base}/artifacts?per_page=100`)return {total_count:data.artifacts.length,artifacts:structuredClone(data.artifacts)};}if(endpoint.endsWith(`/git/commits/${reference.head_sha}`))return structuredClone(commit);if(endpoint.endsWith(`/git/trees/${treeSha}?recursive=1`))return structuredClone(tree);throw Error('Unexpected API path');};
 return {dir,path,reference,entry,producer,certifier,commit,tree,output,api,run:()=>verifyPostcaptureCorrectionSource(request.source,{reference,certificateZipPath:path},api,[entry],()=>structuredClone(output))};
}
for(const [field,value] of [['schema_version','financial-source-certificate-reference-v1'],['repository','wrong/repo'],['run_attempt',0],['head_sha','bad'],['artifact_sha256','0'],['receipt_sha256','0'],['artifact_name','wrong']])test(`reference rejects ${field}`,()=>{const f=fixture();try{assert.throws(()=>parsePostcaptureReference({...f.reference,[field]:value}));}finally{rmSync(f.dir,{recursive:true});}});
test('closed reference and empty production registry',()=>{const f=fixture();try{assert.equal(isPostcaptureReference(f.reference),true);assert.throws(()=>parsePostcaptureReference({...f.reference,allow_failure:true}));assert.throws(()=>verifyPostcaptureCorrectionSource(request.source,{reference:f.reference,certificateZipPath:f.path},f.api),/not independently admitted/);}finally{rmSync(f.dir,{recursive:true});}});
test('direct finite fixture retains distinct false authority and bindings',()=>{const f=fixture();try{const result=f.run();assert.equal(result.job.conclusion,'failure');assert.equal(result.certification.authority,'postcapture_artifact_validation_only');assert.equal(result.certification.publication_authority,'none');assert.equal(result.certification.receipt.producer_execution.producer_cycle_exit_code,0);assert.equal(result.certification.bindings.cycle_sha256,request.failure_boundary.cycle_sha256);assert.deepEqual(Object.keys(result.certification).sort(),['authority','bindings','certifier_job','publication_authority','receipt','reference','reviewed_source_request']);}finally{rmSync(f.dir,{recursive:true});}});
const cases=[
 ['successful source relabel',f=>{f.producer.run.conclusion='success';}],['wrong source job',f=>{f.producer.jobs[0].id++;}],['wrong producer tree',f=>{f.producer.run.head_commit.tree_id='f'.repeat(40);}],
 ['failed companion',f=>{f.certifier.run.conclusion='failure';}],['missing required step',f=>{f.certifier.jobs[0].steps.pop();}],['failed companion step',f=>{f.certifier.jobs[0].steps[0].conclusion='failure';}],['duplicate step',f=>{f.certifier.jobs[0].steps.push(f.certifier.jobs[0].steps[0]);}],
 ['extra job',f=>{f.certifier.jobs.push(f.certifier.jobs[0]);}],['extra artifact',f=>{f.certifier.artifacts.push(f.certifier.artifacts[0]);}],['expired artifact',f=>{f.certifier.artifacts[0].expired=true;}],['changed artifact size',f=>{f.certifier.artifacts[0].size_in_bytes++;}],
 ['truncated code tree',f=>{f.tree.truncated=true;}],['wrong code blob',f=>{f.tree.tree[0].sha='e'.repeat(40);}],['wrong commit parent',f=>{f.commit.parents[0].sha='e'.repeat(40);}],['duplicate reviewed entry',f=>{f.entry.reference={...f.reference,receipt_sha256:'e'.repeat(64)};}],
 ['receipt hash mismatch',f=>{f.output.receipt.authority.publication=true;}],['recorded success fabrication',f=>{f.output.validator_api_snapshot.run.status='completed';f.output.validator_api_snapshot.run.conclusion='success';}],['changed saved producer',f=>{f.output.source_api_evidence.jobs[0].steps[0].name='Different failure';}],
];
for(const [name,change] of cases)test(name,()=>{const f=fixture();try{change(f);assert.throws(f.run);}finally{rmSync(f.dir,{recursive:true});}});

test('two-argument archive wrapper rejects empty registry without subprocess override',()=>{assert.throws(()=>verifyPostcaptureArchive('/nonexistent', 'a'.repeat(64)),/not independently admitted/);});
