#!/usr/bin/env python3
"""Build the FULL US ex-ETF universe ticker list from public exchange listings.

The curated ``us_universe.txt`` is a small liquid subset; this assembles the
*entire* US common-stock universe (NASDAQ + NYSE + AMEX) from a public,
GitHub-hosted mirror of the exchange symbol directories, then filters out ETFs /
ETNs / funds (via the screener's own ``classify_is_etf``) and non-common
securities (warrants, units, rights, preferreds). Only the ticker LIST is
fetched here — no price data — so it runs wherever GitHub is reachable, even when
the market-data vendors are egress-blocked. The output feeds
``fetch_us_universe.py`` for the real-data W3.2 calibration.

  PYTHONPATH=. python3 scripts/build_us_universe.py --out scripts/us_universe_full.txt
  # optional liquidity floor (fewer, more tradeable names):
  PYTHONPATH=. python3 scripts/build_us_universe.py --min-market-cap 300000000
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Allow importing the app's ETF classifier without a live DB.
os.environ.setdefault("DATABASE_URL", "postgresql://local/none")
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from app.services.security_type import classify_is_etf  # noqa: E402

import requests  # noqa: E402

BASE = "https://raw.githubusercontent.com/rreichel3/US-Stock-Symbols/main"
EXCHANGES = ("nasdaq", "nyse", "amex")
# Name tokens that mark a non-common security we don't want in an equity universe.
NON_COMMON_TOKENS = (
    "warrant", "unit", " right", "preferred", "depositary", "debenture",
    "notes due", "%", "convertible",
)


def _fetch(url: str) -> list[dict]:
    r = requests.get(url, timeout=30)
    r.raise_for_status()
    return r.json()


def _market_cap(rec: dict) -> float:
    raw = str(rec.get("marketCap") or "").replace("$", "").replace(",", "").strip()
    try:
        return float(raw)
    except ValueError:
        return 0.0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="scripts/us_universe_full.txt")
    ap.add_argument("--min-market-cap", type=float, default=0.0,
                    help="drop names below this market cap (USD); 0 = keep all")
    args = ap.parse_args()

    records: dict[str, dict] = {}
    for ex in EXCHANGES:
        try:
            recs = _fetch(f"{BASE}/{ex}/{ex}_full_tickers.json")
        except Exception as exc:  # noqa: BLE001
            print(f"WARN: could not fetch {ex}: {exc!r}", file=sys.stderr)
            continue
        print(f"  {ex}: {len(recs)} listed", file=sys.stderr)
        for rec in recs:
            sym = (rec.get("symbol") or "").strip().upper()
            if sym:
                records.setdefault(sym, rec)

    kept: list[str] = []
    dropped = {"etf": 0, "non_common": 0, "bad_symbol": 0, "small_cap": 0}
    for sym, rec in records.items():
        name = rec.get("name") or ""
        low = f" {name.lower()} "
        if classify_is_etf(sym, name):
            dropped["etf"] += 1
            continue
        if any(tok in low for tok in NON_COMMON_TOKENS):
            dropped["non_common"] += 1
            continue
        # Yahoo-compatible tickers only (letters/digits; class shares use '-').
        if not all(c.isalnum() or c in ".-" for c in sym) or len(sym) > 6:
            dropped["bad_symbol"] += 1
            continue
        if args.min_market_cap and _market_cap(rec) < args.min_market_cap:
            dropped["small_cap"] += 1
            continue
        kept.append(sym.replace(".", "-"))  # BRK.B -> BRK-B for yfinance

    kept = sorted(set(kept))
    out = Path(args.out)
    header = (
        "# FULL US ex-ETF universe (NASDAQ+NYSE+AMEX), generated by "
        "build_us_universe.py.\n"
        f"# {len(kept)} common stocks after ETF/non-common filtering. "
        "SPY is fetched separately as the benchmark.\n"
    )
    out.write_text(header + "\n".join(kept) + "\n")

    print(f"\nwrote {len(kept)} symbols -> {out}", file=sys.stderr)
    print(f"  dropped: {dropped}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
