// Display translations only. Original provider keys remain the filter and sort values.
export const INDUSTRY_LABELS = {
  "Aerospace/Defense": "航空宇宙・防衛",
  "Agricultural Operations": "農業",
  "Apparel-Clothing Mfg": "衣料品製造",
  "Apparel-Shoes & Rel Mfg": "靴・関連製造",
  "Auto Manufacturers": "自動車製造",
  "Auto/Truck-Original Eqp": "自動車・トラック純正部品",
  "Auto/Truck-Replace Parts": "自動車・トラック交換部品",
  "Auto/Truck-Tires & Misc": "自動車タイヤ・その他",
  "Banks-Foreign": "銀行・外国",
  "Banks-Midwest": "銀行・米中西部",
  "Banks-Money Center": "銀行・大手都市銀行",
  "Banks-Northeast": "銀行・米北東部",
  "Banks-Southeast": "銀行・米南東部",
  "Banks-Super Regional": "銀行・広域地方銀行",
  "Banks-West/Southwest": "銀行・米西部・南西部",
  "Beverages-Alcoholic": "酒類",
  "Beverages-Non-Alcoholic": "清涼飲料",
  "Bldg-A/C & Heating Prds": "空調・暖房設備",
  "Bldg-Cement/Concrt/Ag": "セメント・コンクリート・骨材",
  "Bldg-Constr Prds/Misc": "建設資材・その他",
  "Bldg-Hand Tools": "手工具",
  "Bldg-Heavy Construction": "重建設",
  "Bldg-Maintenance & Svc": "建物保守・サービス",
  "Bldg-Mobile/Mfg & Rv": "移動式・組立住宅・旅行車",
  "Bldg-Resident/Comml": "住宅・商業建設",
  "Bldg-Wood Prds": "木材製品",
  "Chemicals-Agricultural": "農薬・肥料",
  "Chemicals-Basic": "基礎化学",
  "Chemicals-Paints": "塗料",
  "Chemicals-Plastics": "プラスチック",
  "Chemicals-Specialty": "特殊化学",
  "Comml Svcs-Advertising": "広告サービス",
  "Comml Svcs-Consulting": "コンサルティング",
  "Comml Svcs-Document Mgmt": "文書管理サービス",
  "Comml Svcs-Healthcare": "医療支援サービス",
  "Comml Svcs-Leasing": "リースサービス",
  "Comml Svcs-Market Rsrch": "市場調査",
  "Comml Svcs-Outsourcing": "業務受託",
  "Comml Svcs-Staffing": "人材サービス",
  "Comp Sftwr-Spec Enterprs": "専門業務ソフト",
  "Computer Sftwr-Database": "データベースソフト",
  "Computer Sftwr-Design": "設計ソフト",
  "Computer Sftwr-Desktop": "パソコン用ソフト",
  "Computer Sftwr-Edu/Media": "教育・メディアソフト",
  "Computer Sftwr-Enterprse": "企業向けソフト",
  "Computer Sftwr-Financial": "金融ソフト",
  "Computer Sftwr-Gaming": "ゲームソフト",
  "Computer Sftwr-Medical": "医療ソフト",
  "Computer Sftwr-Security": "セキュリティソフト",
  "Computer-Data Storage": "データ記憶装置",
  "Computer-Hardware/Perip": "コンピューター・周辺機器",
  "Computer-Integrated Syst": "統合システム",
  "Computer-Networking": "ネットワーク機器",
  "Computer-Tech Services": "技術支援サービス",
  "Consumer Prod-Electronic": "消費者向け電子製品",
  "Consumer Prod-Specialty": "専門消費財",
  "Consumer Svcs-Education": "教育サービス",
  "Containers/Packaging": "容器・包装",
  "Cosmetics/Personal Care": "化粧品・身体ケア",
  "Diversified Operations": "複合企業",
  "Elec-Contract Mfg": "電子機器受託製造",
  "Elec-Misc Products": "電子機器・その他",
  "Elec-Scientific/Msrng": "科学・計測機器",
  "Elec-Semicondctor Fablss": "半導体・設計専業",
  "Elec-Semiconductor Equip": "半導体製造装置",
  "Elec-Semiconductor Mfg": "半導体製造",
  "Electrical-Power/Equipmt": "電力設備",
  "Electronic-Parts": "電子部品",
  "Energy-Alternative/Other": "代替エネルギー・その他",
  "Energy-Coal": "石炭",
  "Energy-Solar": "太陽光",
  "Finance-Blank Check": "特別買収目的会社",
  "Finance-Commercial Loans": "事業者向け融資",
  "Finance-Consumer Loans": "消費者金融",
  "Finance-CrdtCard/PmtPr": "カード・決済処理",
  "Finance-ETF / ETN": "上場投資信託・指標連動証券",
  "Finance-Invest Bnk/Bkrs": "投資銀行・証券",
  "Finance-Investment Mgmt": "資産運用",
  "Finance-Mortgage REIT": "不動産担保証券投資信託",
  "Finance-Mrtg&Rel Svc": "住宅ローン関連サービス",
  "Finance-Property REIT": "不動産投資信託",
  "Finance-Publ Inv Fd-Bal": "公募投資信託・バランス型",
  "Finance-Publ Inv Fd-Bond": "公募投資信託・債券型",
  "Finance-Publ Inv Fd-Eqt": "公募投資信託・株式型",
  "Finance-Publ Inv Fd-Glbl": "公募投資信託・世界分散",
  "Finance-Savings & Loan": "貯蓄貸付金融機関",
  "Financial Svcs-Specialty": "専門金融サービス",
  "Food-Confectionery": "菓子",
  "Food-Dairy Products": "乳製品",
  "Food-Grain & Related": "穀物・関連製品",
  "Food-Meat Products": "食肉",
  "Food-Misc Preparation": "食品調製・その他",
  "Food-Packaged": "加工食品",
  "Funeral Svcs & Rel": "葬儀・関連サービス",
  "Group not available": "分類未確認",
  "Hsehold-Appliances/Wares": "家電・家庭用品",
  "Hsehold/Office Furniture": "家庭・オフィス家具",
  "Insurance-Acc & Health": "傷害・健康保険",
  "Insurance-Brokers": "保険仲介",
  "Insurance-Diversified": "総合保険",
  "Insurance-Life": "生命保険",
  "Insurance-Prop/Cas/Titl": "損害・権原保険",
  "Internet-Content": "インターネットコンテンツ",
  "Internet-Network Sltns": "インターネット基盤サービス",
  "Leisure-Gaming/Equip": "賭博・関連機器",
  "Leisure-Lodging": "宿泊",
  "Leisure-Movies & Related": "映画・関連",
  "Leisure-Products": "レジャー用品",
  "Leisure-Services": "レジャーサービス",
  "Leisure-Toys/Games/Hobby": "玩具・ゲーム・趣味",
  "Leisure-Travel Booking": "旅行予約",
  "Machinery-Constr/Mining": "建設・鉱山機械",
  "Machinery-Farm": "農業機械",
  "Machinery-Gen Industrial": "一般産業機械",
  "Machinery-Mtl Hdlg/Autmn": "搬送・自動化機械",
  "Machinery-Tools & Rel": "工作機械・関連",
  "Media-Books": "書籍",
  "Media-Diversified": "総合メディア",
  "Media-Newspapers": "新聞",
  "Media-Periodicals": "定期刊行物",
  "Media-Radio/Tv": "ラジオ・テレビ",
  "Medical-Biomed/Biotech": "バイオ医薬",
  "Medical-Diversified": "総合医療",
  "Medical-Ethical Drugs": "医療用医薬品",
  "Medical-Generic Drugs": "後発医薬品",
  "Medical-Hospitals": "病院",
  "Medical-Long-term Care": "長期介護",
  "Medical-Managed Care": "医療保険・管理医療",
  "Medical-Outpnt/Hm Care": "外来・在宅医療",
  "Medical-Products": "医療製品",
  "Medical-Research Eqp/Svc": "医療研究機器・サービス",
  "Medical-Services": "医療サービス",
  "Medical-Supplies": "医療消耗品",
  "Medical-Systems/Equip": "医療システム・機器",
  "Medical-Whlsle Drg/Suppl": "医薬品・医療用品卸",
  "Metal Prds-Distributor": "金属製品販売",
  "Metal Proc & Fabrication": "金属加工",
  "Mining-Gold/Silver/Gems": "金・銀・宝石採掘",
  "Mining-Metal Ores": "金属鉱石採掘",
  "Office Supplies Mfg": "事務用品製造",
  "Oil&Gas-Cdn Expl&Prod": "石油・ガス探鉱生産（カナダ）",
  "Oil&Gas-Drilling": "石油・ガス掘削",
  "Oil&Gas-Field Services": "油田サービス",
  "Oil&Gas-Integrated": "総合石油・ガス",
  "Oil&Gas-Intl Expl&Prod": "石油・ガス探鉱生産（国際）",
  "Oil&Gas-Machinery/Equip": "石油・ガス機械設備",
  "Oil&Gas-Refining/Mktg": "石油精製・販売",
  "Oil&Gas-Royalty Trust": "石油・ガス権益信託",
  "Oil&Gas-Transprt/Pipelne": "石油・ガス輸送管",
  "Oil&Gas-U S Expl&Prod": "石油・ガス探鉱生産（米国）",
  "Paper & Paper Products": "紙・紙製品",
  "Pollution Control": "環境汚染対策",
  "Real Estate Dvlpmt/Ops": "不動産開発・運営",
  "Retail-Apparel/Shoes/Acc": "衣料・靴・装飾品小売",
  "Retail-Consumer Elec": "家電小売",
  "Retail-Department Stores": "百貨店",
  "Retail-Discount&Variety": "割引・雑貨店",
  "Retail-Drug Stores": "薬局",
  "Retail-Home Furnishings": "家具・室内装飾品小売",
  "Retail-Internet": "通信販売（ネット）",
  "Retail-Leisure Products": "レジャー用品小売",
  "Retail-Mail Order&Direct": "通信・直接販売",
  "Retail-Major Disc Chains": "大手割引店",
  "Retail-Restaurants": "外食",
  "Retail-Specialty": "専門小売",
  "Retail-Super/Mini Mkts": "食品スーパー・小型店",
  "Retail/Whlsle-Auto Parts": "自動車部品小売・卸",
  "Retail/Whlsle-Automobile": "自動車小売・卸",
  "Retail/Whlsle-Bldg Prds": "建材小売・卸",
  "Retail/Whlsle-Jewelry": "宝飾品小売・卸",
  "Security/Sfty": "警備・安全",
  "Soap & Clng Preparatns": "石鹸・洗浄剤",
  "Steel-Producers": "鉄鋼製造",
  "Steel-Specialty Alloys": "特殊合金",
  "Telecom Svcs- Foreign": "通信サービス（外国）",
  "Telecom Svcs-Cable/Satl": "ケーブル・衛星通信サービス",
  "Telecom Svcs-Integrated": "総合通信サービス",
  "Telecom Svcs-Wireless": "無線通信サービス",
  "Telecom-Cable/Satl Eqp": "ケーブル・衛星通信機器",
  "Telecom-Consumer Prods": "消費者向け通信製品",
  "Telecom-Fiber Optics": "光ファイバー",
  "Telecom-Infrastructure": "通信インフラ",
  "Tobacco": "たばこ",
  "Transport-Air Freight": "航空貨物",
  "Transportation-Airline": "航空輸送",
  "Transportation-Equip Mfg": "輸送機器製造",
  "Transportation-Logistics": "物流",
  "Transportation-Rail": "鉄道",
  "Transportation-Ship": "海運",
  "Transportation-Truck": "陸上貨物輸送",
  "Trucks & Parts-Hvy Duty": "大型トラック・部品",
  "Utility-Diversified": "総合公益",
  "Utility-Electric Power": "電力",
  "Utility-Gas Distribution": "ガス供給",
  "Utility-Water Supply": "水道",
  "Wholesale-Electronics": "電子機器卸",
  "Wholesale-Food": "食品卸",
  "Semiconductors": "半導体"
};
export const industryLabel = value => INDUSTRY_LABELS[value] || '分類未確認';
