import {afterEach,expect,it,vi} from 'vitest';
import {captureCurrentFinancialViewport,financialCaptureState,sameCaptureEvaluation} from './capture-current-financial.mjs';
const identity={symbol:'AVT',generation:'g1',date:'2026-10-02'};
const now=Date.parse('2026-10-03T12:00:00Z');
function ready(){vi.spyOn(Date,'now').mockReturnValue(now);document.body.innerHTML=`<div class="symbol-title"><h2>AVT</h2></div><button id="detail-tab-financial" aria-selected="true"></button><section class="financial-evidence-panel">財務の確認時刻 ${new Date(now).toISOString()}<li id="financial-evidence-annual_eps_growth_3y" data-state="fail">Unchanged synthetic source</li></section>`;globalThis.__expiryDiagnostic={workers:[{id:1,request:{operation:'research',evaluation:{generation:'g1',evaluationEpoch:1,now:now-100}},delivered:{date:identity.date,generation:'g1',evaluation_epoch:1,evaluated_at:now-100,next_expiry_at:now+1}}],events:[]};}
afterEach(()=>{vi.restoreAllMocks();delete globalThis.__expiryDiagnostic;document.body.innerHTML='';});
it('requires matching current worker generation, epoch and evaluation plus the selected financial DOM',()=>{ready();expect(financialCaptureState(identity).ready).toBe(true);for(const field of ['generation','evaluation_epoch','evaluated_at']){const d=globalThis.__expiryDiagnostic.workers[0].delivered,old=d[field];d[field]='wrong';expect(financialCaptureState(identity).ready).toBe(false);d[field]=old;}globalThis.__expiryDiagnostic.workers[0].delivered.next_expiry_at=now;expect(financialCaptureState(identity).ready).toBe(false);});
it('withholds ready while a new prepare request has no delivered completion, even if old DOM is visible',()=>{ready();globalThis.__expiryDiagnostic.workers.push({id:2,request:{operation:'prepare',evaluation:{generation:'g1',evaluationEpoch:2,now}}});expect(financialCaptureState(identity).ready).toBe(false);});
it('rejects loading, wrong selected symbol, lost tab and stale panel clock',()=>{ready();const original=document.body.innerHTML;for(const alteration of [html=>html+'<p role="status">銘柄と分析根拠を読み込んでいます…</p>',html=>html.replace('>AVT<','>MRVI<'),html=>html.replace('aria-selected="true"','aria-selected="false"'),html=>html.replace(new Date(now).toISOString(),new Date(now-10000).toISOString())]){document.body.innerHTML=alteration(original);expect(financialCaptureState(identity).ready).toBe(false);}});
it('keeps the failed screenshot and reacquires/rescrolls after expiry before accepting the new epoch',async()=>{const first={ready:true,worker_id:1,generation:'g1',epoch:1,evaluated_at:100,fingerprint:'annual-fail',next_expiry_at:150,now:149,symbol:'AVT'},pending={ready:false,now:150,symbol:null},second={...first,worker_id:2,epoch:2,evaluated_at:200,now:200,next_expiry_at:300};const states=[first,first,pending,second,second,second];const geometry=()=>{},report={};const scroll=vi.fn(),capture=vi.fn(async n=>`attempt-${n}.png`),validateCurrent=vi.fn();const page={waitForFunction:vi.fn(),evaluate:vi.fn(async fn=>fn===geometry?{targets:[]}:states.shift())};const result=await captureCurrentFinancialViewport({page,identity,selectors:['#annual'],geometry,checkGeometry:()=>{},scroll,capture,validateCurrent,report});expect(report.attempts.map(x=>x.status)).toEqual(['expiry-during-capture','current-capture']);expect(report.attempts[0].path).toBe('attempt-1.png');expect(scroll).toHaveBeenCalledTimes(2);expect(validateCurrent).toHaveBeenCalledTimes(2);expect(result.path).toBe('attempt-2.png');});
it('does not retry or hide a genuine stable geometry failure',async()=>{const s={ready:true,worker_id:1,generation:'g1',epoch:1,evaluated_at:100,fingerprint:'fail'},geometry=()=>{},report={};const page={waitForFunction:vi.fn(),evaluate:vi.fn(async fn=>fn===geometry?{}:s)};await expect(captureCurrentFinancialViewport({page,identity,selectors:['#annual'],geometry,checkGeometry:(_g,check)=>check(false,'hidden annual metadata'),scroll:vi.fn(),capture:async()=> 'retained.png',validateCurrent:vi.fn(),report})).rejects.toThrow('hidden annual metadata');expect(report.attempts).toHaveLength(1);expect(report.attempts[0]).toMatchObject({status:'geometry-failed',path:'retained.png'});expect(sameCaptureEvaluation(s,{...s,fingerprint:'changed'})).toBe(false);});
